### ISSUE TITLE
Fix parser error when Jdi generator launched with http scheme 

### ISSUE THREAD

**Issue by epam-ocherniavskaia** [jdi-testing/jdi-dark#424]
Lanching   _java -jar target/DarkGenerator.jar generate -i http://petstore.swagger.io/v2/swagger.json -o ./sample2 -p com.petshop_ gives error (Run on Mac OS).

 java -jar target/DarkGenerator.jar generate -i http://petstore.swagger.io/v2/swagger.json -o ./sample2 -p com.petshop
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://petstore.swagger.io/v2/swagger.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://petstore.swagger.io/v2/swagger.json
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
</body>
</html>
"; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1917)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:194)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:83)
        at com.epam.jdi.generator.CodegenConfigurator.build(CodegenConfigurator.java:225)
        at com.epam.jdi.generator.Generate.run(Generate.java:121)
        at com.epam.jdi.generator.SwaggerCodegenJDI.main(SwaggerCodegenJDI.java:15)
Exception in thread "main" java.lang.RuntimeException: The swagger specification supplied was not valid
        at com.epam.jdi.generator.CodegenConfigurator.build(CodegenConfigurator.java:228)
        at com.epam.jdi.generator.Generate.run(Generate.java:121)
        at com.epam.jdi.generator.SwaggerCodegenJDI.main(SwaggerCodegenJDI.java:15)

**Https scheme works correctly
java -jar target/DarkGenerator.jar generate -i https://petstore.swagger.io/v2/swagger.json -o ./sample2 -p com.petshop.**

**Comment by pnatashap** [comment]
CodegenConfigurator is not a part of jdi-dark
