### ISSUE TITLE
SOAP services doesn't work on JDK 16

### ISSUE THREAD

**Issue by pnatashap** [jdi-testing/jdi-dark#480]
There are 22 failed tests on JDK 16 
Error:  checkRegistration12(com.epam.jdi.httptests.examples.soap.HerongYangServiceTests)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at com.epam.jdi.httptests.examples.soap.HerongYangServiceTests.checkRegistration12(HerongYangServiceTests.java:56)

Error:  checkGeocodeAddressNonParsed(com.epam.jdi.httptests.examples.soap.GeoServicesTests)  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at com.epam.jdi.httptests.examples.soap.GeoServicesTests.checkGeocodeAddressNonParsed(GeoServicesTests.java:24)

Run https://github.com/jdi-testing/jdi-dark/runs/3714178375?check_suite_focus=true

**Comment by pnatashap** [comment]
Works fine on jdk 16
